In [316]:
from sklearn.datasets import make_classification
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,r2_score,accuracy_score
from sklearn import metrics
import pandas as pd
import numpy as np
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [317]:
a=pd.read_csv(r"C:\Users\Jhanvi\OneDrive\Documents\corrected train set.csv")  #reading training set
test=pd.read_csv(r"C:\Users\Jhanvi\OneDrive\Documents\week 1 test.csv")          #reading test set

answer=pd.read_csv(r"C:\Users\Jhanvi\OneDrive\Documents\week 1 test.csv")         #reading same test set again to use in last part



Here we are not using ( product_code) in prediction as training and test have only 'C' as common product.
Assigning random values like 1,2,3,4 to respective materials as we have common types in attributes 0 and 1.


In [318]:
#a['product_code'].replace({"A":1,"B":2,"C":3,"D":4,"E":5},inplace=True)
a['attribute_0'].replace({"material_5":1,"material_6":2,"material_7":3,"material_8":4,},inplace=True) #gave random values to attributes
a['attribute_1'].replace({"material_5":4,"material_6":3,"material_7":2,"material_8":1},inplace=True) #treated attributes 0 and 1 as different so gave different unequal value
a['attribute_3'].replace({5:9 ,6:8 ,8:7 ,9: 6},inplace=True)       # assuming same values in attributes 2 and 3 are unequal

#test['product_code'].replace({"A":1,"B":2,"C":3,"D":4,"E":5},inplace=True)
test['attribute_0'].replace({"material_5":1,"material_6":2,"material_7":3,"material_8":4},inplace=True)
test['attribute_1'].replace({"material_5":4,"material_6":3,"material_7":2,"material_8":1},inplace=True)
test['attribute_3'].replace({5:9 ,6:8 ,8:7 ,9: 6},inplace=True)   


 Dropping of unused columns from both training and test data
 Here iam not using product_code as input has mostly A,B,C but test data has mostly D,E

In [319]:
x=a.drop(['id','failure','product_code'],axis=1)
xtest=test.drop(['id','product_code'],axis=1)
#xtest['attribute_1'].isnull().any()
#xtest['attribute_1'].value_counts()       #check whether any null values are still there

In [320]:
y=a['failure']                        

In [321]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2, random_state=1)       #splitting data in 80:20 ratio

Fill missing values using their mean by Simpleimputer

In [322]:
from sklearn.impute import SimpleImputer

# Imputation
my_imputer = SimpleImputer()
X_train = pd.DataFrame(my_imputer.fit_transform(x_train))
X_valid = pd.DataFrame(my_imputer.transform(x_test))
Xtest=pd.DataFrame(my_imputer.fit_transform(xtest))        # Filling missing values in test data given in week1 test csv file

# Imputation removed column names; put them back
X_train.columns = x_train.columns
X_valid.columns = x_test.columns
Xtest.columns=xtest.columns

SCALING FEATURES 

In [323]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_trai=sc.fit_transform(X_train)     #data obtained after scaling X_train
X_tes=sc.transform(X_valid)           #data obtained after scaling X_valid
Xtest=sc.fit_transform(Xtest)           #scaling the test data given in week1 test file csv

In [324]:
log_reg = LogisticRegression()      #logistic regression model
log_reg.fit(X_trai, y_train)

LogisticRegression()

In [325]:
y_pred=log_reg.predict(X_tes)            # predicti0n after scaling of x_valid data

In [326]:
cm=confusion_matrix(y_test,y_pred)      #confusion matrix to know the accuracy

In [327]:
cm

array([[2541,    2],
       [ 679,    0]], dtype=int64)

In [328]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)                   # meaasuring the accuracy of model

0.7886405959031657

In [329]:
y_pred[:100]                                     # just typing some values of y_pred to see result


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [330]:
y_prob=log_reg.predict_proba(X_tes)[:,1]                   #real probability of above data


In [331]:
y1pred=log_reg.predict(Xtest)                                  #using the model to predict the test data given in week1 test csv file
y1pred[:50]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

In [332]:
y1_prob=log_reg.predict_proba(Xtest)[:,1]                           # gives the probability of obtaining 1

In [333]:
y1_prob[:50]                                                          #printing real probability(of obtaining1) in above data

array([0.23316915, 0.17317153, 0.13842435, 0.1990105 , 0.14783135,
       0.17239551, 0.24178458, 0.14804624, 0.19019431, 0.19513211,
       0.30603309, 0.22807174, 0.1815502 , 0.16334414, 0.18318149,
       0.26481195, 0.21767573, 0.18686957, 0.2382789 , 0.21902798,
       0.25883091, 0.21371256, 0.17503064, 0.21302179, 0.1806568 ,
       0.21996655, 0.28614552, 0.15454922, 0.35350286, 0.17115015,
       0.17018405, 0.17406175, 0.18922618, 0.19543647, 0.26818301,
       0.33581138, 0.281009  , 0.23220992, 0.18330662, 0.15896843,
       0.21501275, 0.19600669, 0.18088842, 0.21927921, 0.24796024,
       0.21683903, 0.16822611, 0.21990688, 0.27808855, 0.23139055])

In [334]:
answer.shape                                  # to get idea on number of rows and columns in week 1 test csv file

(10462, 25)

In [341]:
y1_prob                                       # probability of outcome to be equal to 1

array([0.23316915, 0.17317153, 0.13842435, ..., 0.19671906, 0.17436058,
       0.16887097])

In [342]:
import numpy as np

In [343]:
ce=np.around(y1_prob,1)                          # rounding off to 1 decimal places

In [344]:
answer['probability']=ce # adding the probability column to week1 test csv one

In [347]:
answer['failure']=y1pred

fin=answer[['id','probability','failure']]
fin[fin['probability']>0.5]                             #checking howmany examples have outcome greater than 0.5

id  probability  failure
1000   17108          0.6        1
3182   19290          0.6        1
7194   23302          0.6        1
7771   23879          0.6        1
10006  26114          0.6        1

In [348]:
fin                                                      #final result obtained to me

id  probability  failure
0      16108          0.2        0
1      16109          0.2        0
2      16110          0.1        0
3      16111          0.2        0
4      16112          0.1        0
...      ...          ...      ...
10457  26565          0.3        0
10458  26566          0.2        0
10459  26567          0.2        0
10460  26568          0.2        0
10461  26569          0.2        0

[10462 rows x 3 columns]